import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const skillPath = new URL(
  "../../docs/superpowers/skills/chromosome-3d-idea-to-model/SKILL.md",
  import.meta.url
);

test("chromosome idea-to-model skill exists and encodes v1 guardrails", async () => {
  const skillDoc = await readFile(skillPath, "utf8");

  const requiredPhrases = [
    "name: chromosome-3d-idea-to-model",
    "description: Use when",
    "## Overview",
    "## When to Use",
    "## Workflow",
    "## Output Protocol",
    "## Quick Reference",
    "## Common Mistakes",
    "Degeneracy warning",
    "Baseline Control",
    "Orthogonal Validation",
    "Grounding Notes",
    "phase separation",
    "WORKFLOW BREAKPOINTS & STATE LOCK"
  ];

  for (const phrase of requiredPhrases) {
    assert.match(skillDoc, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }
});

test("chromosome idea-to-model skill defers later stages until mechanism confirmation", async () => {
  const skillDoc = await readFile(skillPath, "utf8");

  const requiredPhrases = [
    "Problem Framing",
    "Competing Mechanisms",
    "Grounding Notes",
    "Consensus",
    "Contested",
    "Heuristic",
    "Software Capability Check",
    "Mandatory Stop Point",
    "User Confirmation Gate"
  ];

  for (const phrase of requiredPhrases) {
    assert.match(skillDoc, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }

  assert.doesNotMatch(skillDoc, /## Simulation Implementation/);
  assert.doesNotMatch(skillDoc, /## Execution Outline/);
});

test("chromosome idea-to-model skill encodes the phase-separation downgrade and degeneracy pause rules", async () => {
  const skillDoc = await readFile(skillPath, "utf8");

  assert.match(skillDoc, /phase separation/i);
  assert.match(skillDoc, /thermodynamic evidence/i);
  assert.match(skillDoc, /Degeneracy warning/);
  assert.match(skillDoc, /Pause simulation recommendation/i);
  assert.match(skillDoc, /two competing control models/i);
});

test("chromosome idea-to-model skill encodes proactive questioning for underspecified biology", async () => {
  const skillDoc = await readFile(skillPath, "utf8");

  assert.match(skillDoc, /Proactive Questions/i);
  assert.match(skillDoc, /ATP-driven/i);
  assert.match(skillDoc, /passive/i);
  assert.match(skillDoc, /Persistence length/i);
  assert.match(skillDoc, /ask clarifying questions/i);
});

test("chromosome idea-to-model skill uses multiple-choice clarification and ends after writing the design doc", async () => {
  const skillDoc = await readFile(skillPath, "utf8");

  assert.match(skillDoc, /multiple-choice/i);
  assert.match(skillDoc, /2-4/i);
  assert.match(skillDoc, /Other/i);
  assert.match(skillDoc, /active end node/i);
  assert.match(skillDoc, /end the conversation/i);
  assert.match(skillDoc, /wait for a new explicit request/i);
});

test("chromosome idea-to-model skill verifies software capability without defaulting to custom-code fallbacks", async () => {
  const skillDoc = await readFile(skillPath, "utf8");

  assert.match(skillDoc, /Software Capability Check/i);
  assert.match(skillDoc, /official docs/i);
  assert.match(skillDoc, /package-native/i);
  assert.match(skillDoc, /package \+ custom extension/i);
  assert.match(skillDoc, /existing model/i);
  assert.doesNotMatch(skillDoc, /standalone custom code/i);
  assert.doesNotMatch(skillDoc, /self-written code/i);
});

test("chromosome idea-to-model skill explores project context without default git and records design docs only after approval", async () => {
  const skillDoc = await readFile(skillPath, "utf8");

  assert.match(skillDoc, /Explore project context/i);
  assert.match(skillDoc, /check files, docs, and any chromosome-related data/i);
  assert.match(skillDoc, /chromosome-related data files/i);
  assert.match(skillDoc, /data-driven polymer model/i);
  assert.match(skillDoc, /physical mechanism polymer model/i);
  assert.match(skillDoc, /one question per message/i);
  assert.match(skillDoc, /Do not default to git/i);
  assert.match(skillDoc, /only inspect git history when the user asks for it/i);
  assert.match(skillDoc, /after the user approves/i);
  assert.match(skillDoc, /docs\/superpowers\/specs\/YYYY-MM-DD-<topic>-design\.md/i);
  assert.match(skillDoc, /generated by/i);
});

test("chromosome idea-to-model skill treats data sources as sufficient during proposal stage", async () => {
  const skillDoc = await readFile(skillPath, "utf8");

  assert.match(skillDoc, /identify data sources/i);
  assert.match(skillDoc, /Do not read detailed parameter files during proposal stage by default/i);
  assert.match(skillDoc, /Only inspect parameter files after the modeling path is approved/i);
});

test("chromosome idea-to-model skill encodes checklist, state machine, after-stage actions, and self-review", async () => {
  const skillDoc = await readFile(skillPath, "utf8");

  assert.match(skillDoc, /## Checklist/i);
  assert.match(skillDoc, /## Workflow State Machine/i);
  assert.match(skillDoc, /State 1:/i);
  assert.match(skillDoc, /Exit gate/i);
  assert.match(skillDoc, /## After This Stage/i);
  assert.match(skillDoc, /If the modeling draft is approved, write the design doc/i);
  assert.match(skillDoc, /If the draft is unresolved, ask one question/i);
  assert.match(skillDoc, /## Self-Review/i);
  assert.match(skillDoc, /stage completeness/i);
  assert.match(skillDoc, /premature handoff/i);
});

test("chromosome idea-to-model skill enforces a hard stop after mechanism decomposition", async () => {
  const skillDoc = await readFile(skillPath, "utf8");

  assert.match(skillDoc, /##\#\[WORKFLOW BREAKPOINTS & STATE LOCK\] \(CRITICAL\)/);
  assert.match(skillDoc, /Mechanism Decomposition -> Minimal Model Building -> Observable Translation -> Software Recommendation/i);
  assert.match(skillDoc, /Never generate the "Minimal Physical Model" or "Execution Outline" during the mechanism brainstorming phase/i);
  assert.match(skillDoc, /You MUST \*\*STOP GENERATING\*\* immediately/i);
  assert.match(skillDoc, /Which of these candidate mechanisms do you prefer to validate first\?/i);
  assert.match(skillDoc, /FORBIDDEN to trigger the minimal model building phase/i);
});
